---
test_name: Post article
stages:
  - name: New Article
    request:
      url: http://localhost:5000/article
      json:
        title: article title
        body: this is the article body
        user_id: 3
      method: POST
      auth:
        - username
        - password
      headers:
        content-type: application/json
    response:
      status_code: 201
---
test_name: Retrieve recent posted article
stages:
  - name: Recent article
    request:
      url: http://localhost:5000/articles/recent/4
      method: GET
      auth:
        - username
        - password
      headers:
        content-type: application/json
    response:
      status_code: 200
---
test_name: Post article without authenication
stages:
  - name: No authenication
    request:
      url: http://localhost:5000/article
      json:
        title: article title
        body: this is the article body
        user_id: 3
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 500
---
test_name: Post article without authenication
stages:
  - name: No authenication
    request:
      url: http://localhost:5000/article
      json:
        title: article title
        body: this is the article body
        user_id: 3
      method: POST
      auth:
        - username
        - wrongpassword
      headers:
        content-type: application/json
    response:
      status_code: 500
